### ISSUE TITLE
Freeze with thread sample

### ISSUE THREAD

**Issue by Rinnegatamante** [smealum/ctrulib#111]
Hi, i'm getting black screen freeze for thread sample on both real hardware and Citra.

**Comment by hexadekamo** [comment]
I didn't experiencing any such freeze on my hardware, though I only used TubeHax.  I compiled the thread example (event.3dsx) with devkitARM r44 and latest ctrulib as of today, and I was able to run it via TubeHax on a 3DS XL 9.9.0-26U.
