### ISSUE TITLE
IO fails when the path contains two dir separators next to one another.

### ISSUE THREAD

**Issue by archshift** [smealum/ctrulib#125]
```cpp
mkdir("/somepath//smth/", 0755)
```
This fails, inconsistent with POSIX mkdir.

**Comment by mtheall** [comment]
Yes this has been observed. The system library doesn't seem to like it. I would say this is sort of nit-picky; just don't pass in such paths.

The simple solution would be to strdup() the path the remove redundant slashes.

**Comment by mtheall** [comment]
Also I don't remember if a trailing slash was problematic or not.
