### ISSUE TITLE
example header

### ISSUE THREAD

**Issue by smealum** [smealum/ctrulib#128]
totally unimportant but i was going through some examples and noticed this : https://github.com/smealum/ctrulib/blob/master/examples/graphics/printing/hello-world/source/main.c#L5-L12

basically i don't think that has anything to do in a source file and should be removed; imo that header should at most contain a description of the example, the author's name and last time modified. if someone wants to see a "big thanks to..." they should look in the readme file imo.

on a equally unimportant note, maybe switch that thing to use // comments rather than /* ?

**Comment by fox8091** [comment]
This has been fixed. Close issue?
