### ISSUE TITLE
GPU_SetScissorTest: function prototype misrepresents usage.

### ISSUE THREAD

**Issue by machinamentum** [smealum/ctrulib#139]
GPU_SetScissorTest(GPU_SCISSORMODE mode, u32 x, u32 y, u32 w, u32 h);
should be
GPU_SetScissorTest(GPU_SCISSORMODE mode, u32 x, u32 y, u32 x1, u32 y1);
The "w" and "h" are misleading as they imply width and height, but the format accepted by GPU_SetScissorTest are screen coordinates, thus
GPU_SetScissorTest(GPU_SCISSOR_NORMAL, x, y, x + width, y + height);
produces the desired result, otherwise if x == width or y == height, nothing is drawn.

**Comment by fincs** [comment]
So it should be left, top, right, bottom then (assuming Y points down).

**Comment by Lectem** [comment]
@fincs I'm not sure left,top,right,bottom is right, especially since we're mostly working on sideway buffers.

**Comment by machinamentum** [comment]
The command is loosely based on [glScissor](https://www.khronos.org/opengles/sdk/docs/man/xhtml/glScissor.xml). x,y specify the lower left corner of the box so 0,0 is the very bottom-right of the screen because of the sideways framebuffer then x1 and y1 specify the upper-right corner (unlike glScissor) of the box. Arguably, you could make it left, bottom, right, top, however, I advise against this as it implies a specific interpretation of how the command is used considering some developers will rotate their scene to accommodate the sideways framebuffer while others may choose to make their game sideways oriented.

**Comment by fincs** [comment]
Please remember that the *physical screens* are sideways, not the framebuffer. Note that it is perfectly possible to use rendered output as a texture - the output should not be tilted.

**Comment by machinamentum** [comment]
Ah I see, then I'd agree to left, bottom, right, top, in that order.

**Comment by fincs** [comment]
Is it confirmed that Y points up, as in the actual behavior of this PICA command?

**Comment by machinamentum** [comment]
I can confirm this. Transferring the GPU output directly to the screen gives these results:
GPU_SetScissorTest(GPU_SCISSOR_NORMAL, 120, 200, 240, 400);
Top-left quarter of the screen is visible. top-right, bottom-right, bottom-left are clipped.

GPU_SetScissorTest(GPU_SCISSOR_NORMAL, 0, 0, 120, 200);
Bottom-right quarter of the screen is visible. Bottom-left, top-left, top-right are clipped.

**Comment by Lectem** [comment]
LCD :

    240
    x
    ^
    |
    |
    |
    |
    |
    +------------------>y 400(320)
  (0,0)

displays only with z in [-1.0,0.0]

gpu with setViewPort(0,0,240,400)



    
    (1.0,1.0)             x 
       +   -   -   -   -  ^ 1.0
                          |
       |                  |
                          |
       |                  |
      y<------------------+
     1.0            (-1.0,-1.0)     



Textures :
    
		v
	1.0 ^
		|
		|
		|
		|
		|
		+------------------>u
	  (0,0)                1.0

**Comment by ic3water** [comment]
Lectem, how can i contact you ?

**Comment by Lectem** [comment]
@ic3water : this issue has nothing to do with it. If you need help for the IES parser open an issue on the IES parser repo.

**Comment by ic3water** [comment]
I have post a commit in your "readme for noobies"

**Comment by uschmann** [comment]
Is this method actually working? I tried to use it in the simple_tri example and it has no effect.
I modified the main loop like this:
while (aptMainLoop())
	{
		gspWaitForVBlank();  // Synchronize with the start of VBlank
		gfxSwapBuffersGpu(); // Swap the framebuffers so that the frame that we rendered last frame is now visible
		hidScanInput();      // Read the user input

		// Respond to user input
		u32 kDown = hidKeysDown();
		if (kDown & KEY_START)
			break; // break in order to return to hbmenu

		// Render the scene
		gpuFrameBegin();
		GPU_SetScissorTest(GPU_SCISSOR_NORMAL, 0, 0, 20, 20);
		sceneRender();
		gpuFrameEnd();
		gpuClearBuffers(CLEAR_COLOR);

		// Flush the framebuffers out of the data cache (not necessary with pure GPU rendering)
		//gfxFlushBuffers();
	}

**Comment by uschmann** [comment]
Ignore my last comment. It works in real Hardware. Scissortest is mit yet implemented properly in citra.
