### ISSUE TITLE
AM structure naming

### ISSUE THREAD

**Issue by smealum** [smealum/ctrulib#141]
looking at https://github.com/smealum/ctrulib/blob/master/libctru/include/3ds/services/am.h currently and i don't like the name of the structure. two things :

- it's not a list, it's a list entry, so I'd rather call it either Title, TitleEntry or TitleListEntry
- it doesn't respect the naming conventions set by every other service; it should have AM_ prepended to it. sure that's mostly for service call functions, but there's precedent for structures also, cf FS and GSP headers 

if noone objects I'll be making these changes pretty soon. mostly posting this issue in case someone has a preference regarding the name and so that there's a record of the change for people who already use that code.

**Comment by smealum** [comment]
tagging @profi200 since he apparently wrote some of that code.

**Comment by profi200** [comment]
Should not be a problem. Breaks a few apps but whatever :p

**Comment by Steveice10** [comment]
This was fixed a while back in great-refactor. Just leaving here as a note.
