### ISSUE TITLE
GPU_Reset seems to use the wrong GSP command buffer

### ISSUE THREAD

**Issue by aroulin** [smealum/ctrulib#144]
https://github.com/smealum/ctrulib/blob/master/libctru/source/gpu/gpu.c#L218

```void GPUCMD_Run(u32* gxbuf)``` wants gxbuf, i.e. the GSP command buffer, as argument but is given the GPU command buffer ```gpuBuf``` instead.

I have tracked down the use of this ```gxbuf``` argument until ```GX_SetCommandList_First``` and ```GSPGPU_SubmitGxCommand``` and it does not seem it is a misnamed variable.

#143 with 73e0267ae472a3c8ca0b897ab5967427458861b6 tried a simple fix but it broke the gpu, see image (it was merged a bit too fast)
![image1](https://cloud.githubusercontent.com/assets/5475997/9069914/87b5a79e-3aec-11e5-80b5-79514616a902.JPG)

**Comment by Lectem** [comment]
Other GPU apps could simple be broken due to the configuration of some registers. I think that ctrulib shouldn't hardcode the reset sequence, but use known registers instead. Plus some registers are set twice, once from the asm reset sequence and once from the function.

**Comment by fincs** [comment]
The old GPU API is deprecated in great-refactor, so therefore this issue is obsolete since applications are expected to no longer use GPU_Reset.
