### ISSUE TITLE
CSND won't load audio from subdirectories that are lower than 1 level

### ISSUE THREAD

**Issue by Kfeavel** [smealum/ctrulib#160]
For example, lets say I have a file called "audio.bin", that has already been tested and does indeed play correctly. If I were to load "audio.bin" from the root directory (/audio.bin), CSND would execute correctly. However, if I were to move it to a directory lower than 1 level (/folder1/folder2/audio.bin), it won't load at all, even if it is the same file. I've already checked the directory names against my code, and they do match up, so it has to be CSND.

**Comment by Steveice10** [comment]
CSND doesn't take file names, how could it be CSND and not your file reading code?

**Comment by plutooo** [comment]
Did you try moving the file a few additional levels, like so:
/this/is/not/csnd/related.bin

**Comment by Kfeavel** [comment]
Yes, I've tried multiple levels and it seems to only read .bin files on higher levels. Also, here is the file reading code:

    FILE *file = fopen(audio, "rb");
    fseek(file, 0, SEEK_END);
    off_t size = ftell(file);
    fseek(file, 0, SEEK_SET);
    buffer = linearAlloc(size);
    off_t bytesRead = fread(buffer, 1, size, file);
    fclose(file);
    // Audio MUST be at bitrate 32000, in 16bit headerless PMC format for this to work.
    // I'm looking at you, future themers!
    CSND_SetVol(8, 1, 1);
    csndPlaySound(8, SOUND_FORMAT_16BIT | SOUND_REPEAT, 44100, 1, 0, buffer, buffer, size);
    linearFree(buffer);

**Comment by Steveice10** [comment]
Have you checked if the file functions are resulting in errors? Also, I'm not sure whether you can free the buffer right after calling csndPlaySound or if it needs it while playing.

**Comment by Kfeavel** [comment]
I've run it using Citra-Emu and it threw a few errors, but none of them related to CSND or file reading. I'll take your suggestion though and try keeping the buffer until the sound is no longer needed.

**Comment by profi200** [comment]
You should generally not free buffers as long as they are used in any way.

**Comment by Kfeavel** [comment]
@profi200, will do. Thanks for the advice.

**Comment by mtheall** [comment]
```
FILE *file = fopen(audio, "rb");
```
What is the value of " audio"

**Comment by Kfeavel** [comment]
@mtheall the value is "/brew/audio/themes/default/audio.bin"

**Comment by profi200** [comment]
You must have some other problem in your code because it makes no difference if you free or not (except everything can allocate there and overwrite your audio data if you free the buffer).

**Comment by Kfeavel** [comment]
@profi200 Yeah, I understand that. I'm confused as to where the code is going wrong, but even if I get the audio to play, it still won't load a file from a few levels down, like listed above. (i.e. /brew/themes/default/audio.bin)

**Comment by Kfeavel** [comment]
Also, @profi200, all of my audio code is listed above. Nothing more, nothing less.

**Comment by yellows8** [comment]
You're not checking for errors. Try printing "size" and "bytesRead"(on hardware).

"Also, that last line that everyone said to leave out ( linearFree(buffer); ), I have to have it or the audio won't play." You may have an issue elsewhere, can you gist/whatever *all* of your code(not just audio)?

**Comment by Kfeavel** [comment]
@yellows8 Here ya go: https://github.com/Kfeavel/3ds_new_hb_menu
As you can tell, its just a fork of Smealum's launcher. Just trying to add more features to it (such as audio, themes and settings.)

**Comment by Kfeavel** [comment]
Found the problem. Duplicate variables in seperate classes. Even after fixing this though, the folder issue still remains.

**Comment by yellows8** [comment]
Uh, you really shouldn't have build/ in git.

"the folder issue still remains." In the commented out code, you have this relative path: "brew/themes/default/music.bin". While in a previous comment you had an absolute path. Are you sure the file actually exists at the relative path location?

**Comment by Kfeavel** [comment]
@yellows8 I've tried it both ways without success. The program sits on the top directory so even if it were relative, it *should* still yield the same results.

**Comment by yellows8** [comment]
Did you ever check these values? https://github.com/smealum/ctrulib/issues/160#issuecomment-136809905

**Comment by Kfeavel** [comment]
@yellows8 I ran it using Citra on Windows (easier to see the log output) and it threw some warnings, but no errors. The audio played correctly on my real 3DS when I fixed the code, but the file was on the top level and not in the folder. I can re-log all the values and warning and post the results here later when I have my 3DS with me.

**Comment by Kfeavel** [comment]
This is what Citra dumped when I ran the program for about a minute or so:
https://www.dropbox.com/s/m1ak870gqlhhhsm/output.txt?dl=0

**Comment by yellows8** [comment]
None of that log is relevant to your branch, except for maybe the GetPointer one(don't know if the original hbmenu triggers that or not).

**Comment by Kfeavel** [comment]
@yellows8 Alright, I'll set up a temporary console and log the results from an actual 3DS. I was wondering if that log pertained mostly to Citra instead of the hbmenu.
