### ISSUE TITLE
audio/mic example behaves strangely

### ISSUE THREAD

**Issue by hexadekamo** [smealum/ctrulib#168]
The mic example's README says it can record roughly 32 seconds of audio. But when I try it, it only plays back a couple seconds of audio, nothing at all, or some duration between the two.

This may not be a proper solution (I wouldn't know), but it turns out if you take line 58 of main.c:
`audiobuf_pos+= MIC_ReadAudioData(&audiobuf[audiobuf_pos], audiobuf_size-audiobuf_pos, 1);`
and change that final argument `waitforevent` from 1 to 0, it'll record and play back the full 32 seconds pretty much fine.

Example was compiled with devkitARM r44 with latest ctrulib and launched via TubeHax on a 3DS XL with firmware 10.0.0-27. (Same thing happened on 9.9.0-26 too.)

**Comment by Cruel** [comment]
I did the same and confirm that it seems to work.

Additionally, I noticed that the first ~1 second of audio gets cut off in playback, as if  1) the mic doesn't start recording immediately or 2) the sharedmem is being read from an improper offset.

**Comment by Garcia98** [comment]
I'm also having the same problem than @Cruel has anyone been able to fix it?

**Comment by Rinnegatamante** [comment]
I "solved" it by just cutting the first second if it can be helpful ( https://github.com/Rinnegatamante/lpp-3ds/blob/master/source/luaSound.cpp#L1138-L1174 )

**Comment by profi200** [comment]
The MIC example broke since the last big changes. Probably the threading broke it. Well, it is  broken but does not correctly work imho.

**Comment by Garcia98** [comment]
@Rinnegatamante Good :+1:
But a *proper* fix is always better

@profi200 Which last big changes? It works fine for me using great-refactor branch of ctrulib (and changing waitforevent argument to 0).

**Comment by fincs** [comment]
MIC should probably be overhauled in great-refactor anyway.

**Comment by Steveice10** [comment]
MIC and its example should be fixed in great-refactor.
