### ISSUE TITLE
Broken socketing on Ninjhax 2.X with big sized homebrews

### ISSUE THREAD

**Issue by Rinnegatamante** [smealum/ctrulib#171]
It seems socketing is corrupted if used with some other services on with NH 2.X and relative haxs.

The same code working fine on 1.1b report errors when sending for server-type sockets and connecting for client-type sockets for my LUA interpreter (for example FTP give ECONNREFUSED on NH 2.x and Socket.connect() gives "Failed connecting server" error when executing this piece of code:

int err = connect(my_socket->sock, (struct sockaddr*)&my_socket->addrTo, sizeof(my_socket->addrTo));
    if (err < 0 ) return luaL_error(L, "Failed connecting server.");

**Comment by Lectem** [comment]
Are you using the same builds of the hb lancher in both cases ?

**Comment by Rinnegatamante** [comment]
On NH1.1b i'm using boot.3dsx which came with first release of 1.1b version.
On NH2.X who tested for me is using latest boot.3dsx released by smealum. (The ones who patched emus)

**Comment by Lectem** [comment]
I'd suggest trying NH1 with latest boot.3dsx to see if it breaks too

**Comment by Rinnegatamante** [comment]
I'm not using netloader.
I tried now with last boot.3dsx and it works fine on NH1.1b.

**Comment by Lectem** [comment]
This is kind of weird since the HB launcher uses sockets for the netloader and it works just fine

**Comment by Rinnegatamante** [comment]
Don't know if it could be useful, https://github.com/Rinnegatamante/lpp-3ds/blob/master/source/main.cpp

These are the services used by default from lpp-3ds (SOC is initialized only when you start FTP or you want to create a socket).

I tried to comment initializations for: libkhax, Cfgu,  ptm, ac, httpc services but the issue is still here on NH2.X

**Comment by Rinnegatamante** [comment]
I've done other tests and now seems same error appears also on NH1.1b.

Strange thing i found is IP returned by gethostid() on SOC_Initialize() call is set to a LAN IP (For example i get 192.168.1.71) but after few time (like 1 second) the IP is set to another (Online?) IP address (this ip is normally returned when console is offline), in my case, i get 247.7.224.216.

**Comment by Lectem** [comment]
You might want to ask @mtheall about it, but ftbrony and ftpony seems to be doing fine

**Comment by Rinnegatamante** [comment]
I'm using the same code of ftpony.
ftpony works fine on both NH1.1B and NH2 so maybe it's related on the size of homebrews and how they are managed when a 3DSX file is loaded from hb service?

**Comment by Lectem** [comment]
Yeah there seems to be some problems when loading *big* .3dsx under NH2, it's *not* a problem coming from ctrulib but from the payload+hbmenu. 
> [01:15:02] <Lectem> after launching my app or citrAGB (probably others) the SOC_Init fails with d8e06406
> <yellows8> < Lectem> it gets to HBMENU_NETLOADER_UNAVAILABLE_NINJHAX2 <- which is for, you know, booting into a process with SOC access....

It seems that sometimes the HB launcher won't have/find a SOC handle. 

Now, why does it always trigger after loading some *big* homebrews and not on smaller ones such as ftbrony which indeed uses SOC, I don't know.

**Comment by Rinnegatamante** [comment]
Is it normal that same thing happens on NH1.1b?

**Comment by Lectem** [comment]
> Is it "normal" that same thing happens on NH1.1b?
Probably a different issue, or a problem that affects both but hardly detectable.
The gethostid bug could also be a quirk of the OS I suppose ?

**Comment by Rinnegatamante** [comment]
At least on NH1.1b, the problem seems not related to hb size cause i tried with an older version of lpp-3ds which was bigger then the latest one ( https://github.com/Rinnegatamante/lpp-3ds/tree/a3f65d10c6c463ff8bf0fa961cf7706aa1fa9c89 ) and FTP works fine.
The strange thing is that, if you see lpp-3ds history, there are no big changes in FTP utility so i really don't know where the problem is.

**Comment by smealum** [comment]
on 2.x, try creating an xml file that has the same name as your 3dsx (test.3dsx -> test.xml) and is in the same directory and contains the following :

<services autodetect="false">
	<request priority="1">soc:U</title>
</services>

**Comment by shutterbug2000** [comment]
For httpc at least, the xml file doesn't seem to resolve it.

**Comment by smealum** [comment]
it currently wont fix http:C, i'm only asking for soc:U

**Comment by Rinnegatamante** [comment]
It seems to not work (I always get a crash when exiting my app, get a wrong IP from gethostid() (Like soc:U failed to initialize) and trying to create sockets resolve in a binding error.)

**Comment by yellows8** [comment]
Regarding gethostid(): the service command is probably returning an error, resulting in whatever was on the sysmodule stack for the output u32 being junk(like many other service cmds).

**Comment by Rinnegatamante** [comment]
If i'm not wrong, 247.7.224.216 is an intranet IP so, according to SOC:u failing to start, i think it's normal gethostid returns such IP ( http://www.speedguide.net/ip/247.7.224.216 ).

**Comment by yellows8** [comment]
That's "f707e0d8", aka 0xd8e007f7. Clearly not an IP address. http://3dbrew.org/wiki/SVC#Kernel_error-codes

**Comment by Rinnegatamante** [comment]
Found other strange things (this time on NH 1.1b but i think they are the same on NH2), with this piece of code: http://pastebin.com/M4erXPNb

Socketing works fine.
If i de-comment the piece of code relative to graphic, soc:U fail to initialize (and this piece of code, without socketing will never be executed) :/

**Comment by Rinnegatamante** [comment]
Nothing changed with NH2.5. Codes working on NH1.1b still don't work on it.

**Comment by Lectem** [comment]
Could you please provide a simple example that shows the bug ? and in C with ctrulib functions only.

**Comment by Rinnegatamante** [comment]
It depends on how big the file is so i can't provide a SIMPLE example, sorry. 

Anyway you can give a shoot to this which is bugged: https://github.com/Rinnegatamante/SMuRF

**Comment by Lectem** [comment]
Sorry but I can't build that project, it uses a way too outdated version of ctrulib (pre CSND refactor...)

**Comment by retrohead** [comment]
I've built a large-ish 3dsx which has a binary of 650kb without any romfs files. It boots fine in citra and on nh1.1b but its giving a red screen on nh2.2.

Could this be the same problem? I've done a lot of testing on the code and it falls over as soon as the binary hits a certain size. I'm porting an old ds project so I am uncommenting functions as I go and its falling over no matter which bit I add.

It was working in citra and this issue is the only thing I could find similar. I was surprised to find it work OK nh2. Its only a game and has no socketing so I think nh2 is maybe a bit too feature bloated?

**Comment by retrohead** [comment]
I meant to say I was surprised to find it work on 1.1b. Can't find an edit comment button.
