### ISSUE TITLE
consoleDrawChar is missing from header file

### ISSUE THREAD

**Issue by flarn2006** [smealum/ctrulib#175]
I'm assuming this isn't a "private" function, as it's the only way (AFAIK) to display the characters that are given special handling (tab, newline, etc.)

**Comment by Lectem** [comment]
Using printf and a string with \n or \t works fine

**Comment by flarn2006** [comment]
No, I mean to actually *display* the characters. Without doing a newline or tab or anything.

**Comment by fincs** [comment]
People aren't really supposed to print out control characters that already have a meaning to the tty.

**Comment by flarn2006** [comment]
Then how are you supposed to display those characters directly?

**Comment by fincs** [comment]
I doubt they even have an associated glyph.

**Comment by flarn2006** [comment]
They do.

**Comment by fincs** [comment]
What glyph?

**Comment by flarn2006** [comment]
Just like code page 437.

**Comment by fincs** [comment]
Current console code does not take character encoding into account; blindly mapping bytes into indices into the internal font instead, which so happens to follow CP437. It is in our plans to implement proper UTF-8 support, and the supported way to print those special glyphs that were assigned to control codes in CP437 will be actually using the proper Unicode codepoints that have been reserved for those glyphs, such as U+25D9 ◙ (mapped to LF in CP437) or U+25CB ○ (mapped to HT).
