### ISSUE TITLE
Cfg:GetSystemModel wrong return value

### ISSUE THREAD

**Issue by Rinnegatamante** [smealum/ctrulib#194]
Calling this on an O3DS returns me 1 as return value ( http://3dbrew.org/wiki/Cfg:GetSystemModel )

**Comment by yellows8** [comment]
Sounds like yet another case of ignoring the result-code......

**Comment by smealum** [comment]
https://github.com/smealum/ctrulib/blob/master/libctru/source/services/cfgu.c#L66-L78

code looks fine to me. have you checked the return value to see if tehre are any errors ?

**Comment by Rinnegatamante** [comment]
It seems getModel returns an error: 0xD900182F.

**Comment by yellows8** [comment]
Don't know why that would happen if you initialized cfgu correctly, unless you corrupted the cfgu handle somehow.

**Comment by Rinnegatamante** [comment]
I use other cfgu functions without any problem (like CFGU_SecureInfoGetRegion, CFGU_GetSystemLanguage, CFGU_GetConfigInfoBlk2). This seems to be the only one causing this kind of errors.

**Comment by profi200** [comment]
Passing wrong parameters/a bad pointer? Try it outside of your lua environment on the same 3DS.

**Comment by Rinnegatamante** [comment]
Nvm, updating to last ctrulib solved the issue ;)
