### ISSUE TITLE
Weird sound issue when quitting whilst a looped sound is playing with csnd

### ISSUE THREAD

**Issue by VideahGams** [smealum/ctrulib#199]
Having a looped sound playing with csnd when a homebrew application is quitting causes some funky behaviour.

When loading other homebrew, high pitched noises can be heard, and loading other homebrew that uses sound can cause distortion. 

Loading the homebrew the looped sound originated from causes the sound to be played, even if it shouldn't be.

I don't have good footage, but @shutterbug2000 recorded a similar issue with BreadBox https://www.youtube.com/watch?v=BPf4AUWewqM

Even stopping all channels on exit doesn't fix it.

**Comment by Rinnegatamante** [comment]
Same thing happens with old CSND wrapper used by lpp-3ds. It's a not-very-much recent issue appeared with some ctrulib update i think.

**Comment by StapleButter** [comment]
Pretty sure the cause is that the homebrew forgets to stop that channel before exiting. Thus it continues playing whatever is where it's set to read from.

**Comment by VideahGams** [comment]
But I'm stopping all channels on exit, and the problem still happens.

**Comment by WoniMK7** [comment]
It shouldn't happen [here](https://github.com/WoniMK7/Muzik-player/blob/master/source/main.c) if I understand your problem, markinwap managed to fix this.
