### ISSUE TITLE
dspInit() causes a delayed deadlock when appStatus == APP_NOTINITIALIZED

### ISSUE THREAD

**Issue by aliaspider** [smealum/ctrulib#200]
specifically, calling `DSP_UnloadComponent` when the status is still `APP_NOTINITIALIZED` seems to be the problem.
this doesn't affect 3dsx builds started from the HBL currently since they start with the `APP_RUNNING` status.

adding 
```
if(!aptGetStatus())
   aptWaitStatusEvent(); 
```
before this line https://github.com/smealum/ctrulib/blob/great-refactor/libctru/source/services/dsp.c#L17  prevents the deadlock.

**Comment by fincs** [comment]
Fixed with 6bdfa1a.
