### ISSUE TITLE
No sound with ndsp.

### ISSUE THREAD

**Issue by Rinnegatamante** [smealum/ctrulib#202]
I'm trying to port luaSound module of my interpreter to dsp service (cause csnd:SND seems broken for most things). I can successfully init ndsp ( https://github.com/Rinnegatamante/lpp-3ds/blob/master/source/luaSound.cpp#L974-L992 ) but when i try to play a mono WAV file (PCM-16 encoded) i get no sound ( https://github.com/Rinnegatamante/lpp-3ds/blob/master/source/luaSound.cpp#L1027-L1043 ).

**Comment by Lectem** [comment]
I think it probably is a misuse of the API.
My best guess is : You are calling ndspChnWaveBufClear https://github.com/Rinnegatamante/lpp-3ds/blob/master/source/luaSound.cpp#L1036 after setting your channel information

Other than that, a few remarks :

* I don't see anywhere a free for https://github.com/Rinnegatamante/lpp-3ds/blob/master/source/luaSound.cpp#L1037 , ndsp will not call free it for you
* [This](https://github.com/Rinnegatamante/lpp-3ds/blob/f202d617edc0bf1f6f4de3c79cb45e54878593a0/source/luaAudio.cpp#L82 ) is useless since it is the same member (union) . If you are planning to use different formats you could just use data_vaddr member and call it a day
* Just in case, try using calloc instead of malloc or initialize the ndspWaveBuf::status member to NDSP_WBUF_FREE before use

**Comment by Rinnegatamante** [comment]
Tried to switch to calloc and move BufClear before setInterp but nothing changed :/

**Comment by fincs** [comment]
```
ndspSetOutputCount(1);
```
Try removing that line as that regulates something that has nothing to do with the number of channels used.

**Comment by Rinnegatamante** [comment]
Nothing seems to change as stated by my tester. I also tried by myself to run the same code on NH 1.1b (using 0x08 as channel cause using 0x01 crashes 3DS) and it freeze when playWav is called, don't know if it's normal.

**Comment by Rinnegatamante** [comment]
Seems i solved the problem by re-using wavClear after the set things and commenting the SetOutputCount. Now it works also on NH1.1b (using 0x08 as channel).

Does ndsp works also on 3DS/CIA (if dsp::DSP service is included in the workaround)?

**Comment by Rinnegatamante** [comment]
Another issue came off. Same code executed on NH1.1b and on NH2.5 (Not by me on nh 2.5 but by a tester):

On NH 1.1b it works fine. ( http://rinnegatamante.it/original.ogg )
On NH 2.5 it has strange sound ( http://rinnegatamante.it/fullcorruptedaudio.ogg )

File is a Mono Ogg audiofile decoded using vorbisfile + libogg.
On NH 2.5 it was played on channel 0x00, on NH 1.1b it was played on channel 0x08.

I also tried a mono wav file and it works correctly on both NH1.1b and NH2.5 (same channels settings).

Don't know if it's relevant, i switched from no interpolation to linear interpolation.

**Comment by fincs** [comment]
What sample rate is the OGG? There may be problems with audio that is higher than 32728 Hz. Try removing the call to set the interpolation type and see what happens.

**Comment by Rinnegatamante** [comment]
Tried now to use a 32k HZ file and remove the setInterp call but still similar issue (slightly different output probably caused by different samplerate).

**Comment by fincs** [comment]
Note how it is not 327**6**8 Hz but 327**2**8 Hz.

**Comment by Rinnegatamante** [comment]
Samplerate file is 32000 Hz.

**Comment by Rinnegatamante** [comment]
Also added AIFF files support and they works fine. The problem came only with OGG files. I updated also repository with last changes if someone wants to take a look (there are still some things which i need to rewrote like streamOgg and streamWav functions): https://github.com/Rinnegatamante/lpp-3ds/blob/master/source/luaSound.cpp

**Comment by Lectem** [comment]
If it works fine with another format it's probably a misuse of the API or your conversion, in which case this issue should be closed

**Comment by smealum** [comment]
Unfortunately we currently don't really have another good place to ask for
help on this kind of issue (except for IRC, which is not practical for
everyone).

i'm the one who told him to ask for help here so please don't close the
issue until he doesn't have any other questions regarding this.

thanks !

**Comment by Rinnegatamante** [comment]
If the problem is the conversion so why the ogg plays fine on NH 1.1B with the same code?

**Comment by Rinnegatamante** [comment]
I saved the decompressed vorbis audiocodec buffer into a standard PCM16 audiocodec buffer with the 3DS and it looks like the buffer itself is corrupt but this happens only on NH 2.x. Does someone know what could be the problem? It seems like some changes in the payload (?) broke something in the standard C library maybe... 

Here can be found libogg and vorbisfile i'm currently using: https://github.com/Rinnegatamante/lpp-3ds/tree/master/source/include/ogg

**Comment by Rinnegatamante** [comment]
Some other info about this:

It seems the problem looks very similar to what happened when i updated ctrulib version used by lpp-3ds some weeks ago (when i was still using an old CSND wrapper, before the CSND refactor)).
Before the update, OGG played fine on NH 2.1, after it, they started being corrupted on NH 2.1.

I'm quite sure the commit broke vorbisfile/libogg is this: https://github.com/Rinnegatamante/lpp-3ds/commit/ab4827932578dc265de453fb357becb45b83f678

**Comment by Rinnegatamante** [comment]
Solved reverting from mfloat-abi=hard to mfloat_abi=softfp.

**Comment by fincs** [comment]
Instead of reverting the float ABI, try removing `-ffast-math` from the compiler flags.

**Comment by Rinnegatamante** [comment]
Still corrupted with float-abi=hard and no -ffast_math flag.

**Comment by Lectem** [comment]
From irc:
[10:50] (@profi200) Lectem: Outdated *hax 2.5? Earlier versions had stack problems dealing with floatingpoint numbers.

**Comment by ihaveamac** [comment]
I'm the one testing on *hax 2.5. I'm using the latest payloads for ironhax (New 3DS) and oot3dhax (Old 3DS). The date that shows when the hax is starting is 2015-11-03, both before and after updating.

It was said earlier, but with float-abi=hard and -ffast-math removed, ogg audio was corrupted. Worked fine before these changes.
