### ISSUE TITLE
ndspChnWaveBufClear doesn't stop playback

### ISSUE THREAD

**Issue by Rinnegatamante** [smealum/ctrulib#206]
Actually calling this function while the channel is playing some audio doesn't seem to stop playback.

**Comment by fincs** [comment]
[But it does](https://github.com/smealum/ctrulib/blob/great-refactor/libctru/source/ndsp/ndsp-channel.c#L128).

**Comment by fincs** [comment]
The problem appears to be fixed now.

**Comment by Rinnegatamante** [comment]
It seems the issue still happens (at least with looping wavbuffers).

**Comment by Rinnegatamante** [comment]
Re-tested also with non-looping wavbuffers and issue still appears. When clear is called, sound still plays but slowed and distorted.

**Comment by fincs** [comment]
I saw in the other issue that you modified libctru to execute the DSP thread in the SYSCORE. As of now, synchronization primitives do not work correctly across cores, and thus you will run into issues.

**Comment by Rinnegatamante** [comment]
Not at all, seems i found what caused the issue. I was calling a reset before wavclear. Removing it seems to have patched the issue.
