### ISSUE TITLE
Camera Example not working O3DS/ThemeHax 2.5

### ISSUE THREAD

**Issue by kbowen99** [smealum/ctrulib#208]
When I compile and run the camera image example, no image is written to the top framebuffer after pressing 'R'. The console outputs tons of information, but the top framebuffer seems empty.

Screenshots included
![scr_2_top_left](https://cloud.githubusercontent.com/assets/1390008/11021193/7d2b9c4e-85ff-11e5-8089-5466339af515.png)
![scr_2_top_right](https://cloud.githubusercontent.com/assets/1390008/11021194/7d2cdece-85ff-11e5-9b5f-8f8c2ccf20d4.png)
![scr_2_bottom](https://cloud.githubusercontent.com/assets/1390008/11021195/7d2e8008-85ff-11e5-916d-cdb8efff32c3.png)

**Comment by Lectem** [comment]
Related to https://github.com/smealum/ctrulib/commit/76e47c02c807f6dc774bfe3101a4d3f83dcb0ed7  https://github.com/smealum/ctrulib/issues/201 and https://github.com/yellows8/3ds_homemenuhax/issues/22

**Comment by Steveice10** [comment]
@Lectem That isn't related... As you can see on the bottom screen, the CAM commands are erroring.

**Comment by Lectem** [comment]
@Steveice10 Yeah, I just read too fast, my bad

**Comment by yellows8** [comment]
Sounds like you didn't copy the example's xml to SD.

**Comment by kbowen99** [comment]
You were right, thought I copied it over, but it failed FTP. Thanks for the help though!
