### ISSUE TITLE
Service Organization Proposal

### ISSUE THREAD

**Issue by Steveice10** [smealum/ctrulib#215]
I'd like to propose some changes, targeted toward the great-refactor branch of course, to make service code more organized. This is purely for feedback on some ideas I had, and if it has enough of a positive response I'll likely start working on a PR for the proposed changes.

**1. Separate services into their own files.**

This is mainly targeted towards services like gsp::Gpu and gsp::Lcd. Currently they are lumped together into a single file, but each have their own unique initialization function and purpose. It would make sense to split services into their own files. Services could be optionally grouped by module within subdirectories, along with their higher-level functions (for example, moving sdmc_dev and romfs_dev into a subdirectory with FS functions).

**2. Separate IPC from higher-level functions.**

Currently, higher level functions are lumped together with IPC functions, with the only distinction being naming convention. This change would separate IPC functions into different source and header files with their own initialization function. That way, a user could make use of IPC in their own way, bypassing ctrulib's higher level management, especially that within initialization functions. They could manage shared memory, setup, etc. however they want. This would also provide a clean separation between IPC and higher-level usage. IPC would have something like "SERVICE_OpenIpc()" to acquire and store the handle in a global variable and "SERVICE_CloseIpc()" to close it, and the current higher-level initialization functions would call these and do their extra management calls afterwards. There could also be something like "SERVICE_GetIpcHandle()" to gain direct access to the opened handle.

After these changes, the source would look something like this for FS:
 * **source/services/fs/fsuser_ipc.c** - fs:USER IPC functions.
 * **source/services/fs/fsfile_ipc.c** - fs:FILE IPC functions.
 * **source/services/fs/fsdir_ipc.c** - fs:DIR IPC functions.
 * **source/services/fs/fsreg_ipc.c** - fs:REG IPC functions.
 * **source/services/fs/fsuser.c** - fs:USER higher-level functions.
 * **source/services/fs/fsfile.c** - fs:FILE higher-level functions.
 * **source/services/fs/fsdir.c** - fs:DIR higher-level functions.
 * **source/services/fs/fsreg.c** - fs:REG higher-level functions.
 * **source/services/fs/sdmc_dev.c** - SDMC devoptab.
 * **source/services/fs/romfs_dev.c** - RomFS devoptab.

**Comment by Lectem** [comment]
1. Indeed
2. Thing is, refcounting was added so that there would be no conflicts when initializing/exiting services multiple times, for example when using libraries. (This way you could for example use sf2d without worrying of trying to initialize the gsp twice etc...). I don't really feel safe with providing the IPC with a custom handle (the only use we can see is with FS, and @fincs had some ideas on how to deal with it).

Other than that, I'm all for having each service(or module?) in its own directory, especially because we could then have both an API header and an error header.

**Comment by Steveice10** [comment]
IPC doesn't necessarily have to have a custom handle, if I'm interpreting you correctly. It would maintain the handle in much of the same way as now, except it would be maintained separately from the higher-level functions, and the function to initialize it wouldn't have all of the extra shared memory, etc. initialization that they come with currently.

**Comment by Lectem** [comment]
Oh, now I see what you mean, "SERVICE_OpenIpc()" would only get the handle ?

**Comment by Steveice10** [comment]
It might've been poor communication with the naming on my part, but basically it would use srvGetServiceHandle, store that in a global variable, and bump up a ref counter. Nothing extra.

**Comment by Lectem** [comment]
I could see a use for this, however we don't really need to split the files for all the services since some are only using raw IPC, with the exception perhaps of init/exit.

I am not sure if we should also provide this "SERVICE_OpenIpc()" for the services which have init == SERVICE_OpenIpc().

**Comment by Steveice10** [comment]
For services that just use raw IPC, I'd be in favor of making said services just in the new IPC form for consistency, and in case for whatever reason a non-IPC form comes about. As for services with higher-level functions but no extra initialization, that'd be a matter of consistency.

**Comment by Lectem** [comment]
Well I personally do not like the idea of appending IPC to 90% of the service calls. I think that the lower/uppercase approach usually speaks for itself

**Comment by Steveice10** [comment]
IPC would not be appended to the function names. They would retain the current lower/uppercase naming convention to distinguish IPC and higher-level functions.

**Comment by fincs** [comment]
I agree with splitting services that are bundled together (e.g. gsp::Gpu and gsp::Lcd) into separate source code files. `sdmc_dev` and `romfs_dev` are not services. I disagree with splitting IPC wrappers from the "higher" level management.

**Comment by Steveice10** [comment]
In regards to splitting services apart, there is the issue of services that are used as alternates for common commands. On one hand, they share common commands, so it might make sense to keep them together, but on the other hand, they do tend to have their own unique commands as well, and it would be ambiguous which service is actually being used when trying to access those unique commands.
