### ISSUE TITLE
Make sure IPC getters are using mask for short/char/bool values

### ISSUE THREAD

**Issue by Lectem** [smealum/ctrulib#217]
I saw a few places where values are not masked while nintendo uses STRB or STRH. We should also make sure that all bool types are masked using 0xFF.
Enum values should be masked depending on the smallest value (usually 0xFF or 0xFFFF). While gcc already stores most of those in bytes or halfwords, it is not guaranteed by the standard.

For example I spotted https://github.com/Steveice10/ctrulib/blob/service-cleanup/libctru/source/services/cam.c#L355 but there are probably many other services suffering from this issue.

**Comment by Steveice10** [comment]
Updated https://github.com/smealum/ctrulib/pull/216 to resolve this.
