### ISSUE TITLE
svc_readProcessMemory/svc_writeProcessMemory return failed!?

### ISSUE THREAD

**Issue by zsword** [smealum/ctrulib#229]
I using svc_openProcess return success, then i using svc_readProcessMemory and svc_writeProcessMemory try to change process memory, but it return failed(looks like b9002020).Please tell me how can i change the process memory?

**Comment by yellows8** [comment]
You need to use a KDebug handle, not KProcess, such as the one from svcDebugActiveProcess().

**Comment by fincs** [comment]
There is a series of things you need to do in order to be able to open a process using the debugging APIs. You may be better off asking in the IRC channel (#3dsdev at EFnet).
