### ISSUE TITLE
synchronization.o  Error!  trying to build Version 1.0.0

### ISSUE THREAD

**Issue by kennyd-lee** [smealum/ctrulib#231]
#include "arm-gnu-eabi/include/sys/lock.h"
typedef int _LOCK_T;
typedef int _LOCK_RECURSIVE_T;
...

#include "synchronization.h"
/// A light lock.
typedef _LOCK_T LightLock;
/// A recursive lock.
typedef _LOCK_RECURSIVE_T RecursiveLock;
...

__ldrex & __strex give "incompatible pointer type" errors when compiling?

the members -> thread_tag, counter are defined were?

Eg.
/opt/radiofreedom/ctrulib-master/libctru/source/synchronization.c:111:7: error: request for member 'thread_tag' in something not a structure or union
   lock->thread_tag = tag;

**Comment by fincs** [comment]
Update to devkitARM r45.

**Comment by kennyd-lee** [comment]
thank-you, I've updated
gcc-4.9.2 --> gcc-5.3.0
binutils-2.25 --> binutils-2.25.1

 I've tried gw_workaround.rsf & makerom and failed !!!

I get complains of 
[RSF ERROR] Unrecognised Key: 'Rom'

if i change 'Rom' --> 'RomFs' in "gw_workaround.rsf"
makerom': malloc(): memory corruption:  ....

**Comment by profi200** [comment]
Compile the latest makerom from source. There is no release yet because it is not tested enough. Report back how it works.

**Comment by fincs** [comment]
makerom is not supported here, sorry. You may have better luck creating an issue in the makerom project.

**Comment by Steveice10** [comment]
@kennyd-lee You'll need to update makerom to the latest source commit for devkitARM r45 compatibility.
