### ISSUE TITLE
makerom fails after updates 

### ISSUE THREAD

**Issue by kennyd-lee** [smealum/ctrulib#232]
I've updated
gcc-4.9.2 --> gcc-5.3.0
binutils-2.25 --> binutils-2.25.1
libctru & citro3d compile just fine 

I've tried use gw_workaround.rsf & makerom and failed !!!

I get complains of
[RSF ERROR] Unrecognised Key: 'Rom'

if i change 'Rom' --> 'RomFs' in "gw_workaround.rsf"
makerom': malloc(): memory corruption: ....

**Comment by profi200** [comment]
This is not a ctrulib issue.

Compile the latest makerom from source. There is no release yet because it is not tested enough. Report back how it works.
Also use the sample rsf files linked in the last release as template for yours.
