### ISSUE TITLE
wprintf or printf with %ls format causes a softlock

### ISSUE THREAD

**Issue by MarcuzD** [smealum/ctrulib#239]
Version: [2feb368dd1dbb3b102a34a254cddc042cdf97319](https://github.com/smealum/ctrulib/tree/2feb368dd1dbb3b102a34a254cddc042cdf97319) (almost-latest)

Example code:
```
#include <3ds.h>
#include <wchar.h>
#include <locale.h>
wprintf(L"This is a test");
//or
printf("This is a bit simpler test, but actually %ls \n", L"it's not");
```

I think the console renderer causes the crash, but I'm not sure.

**Comment by WinterMute** [comment]
wprintf is not supported, sorry.

The console doesn't support unicode of any form atm either.

**Comment by MarcuzD** [comment]
But sadly FSDIR uses wchar_t (in the source it's an u16 array), so how could I store the filename in char* if it contains japanese characters? That's why I'm trying to use wchar_t.

**Comment by fincs** [comment]
wchar_t is 32-bit in devkitARM. You should use the [UTF conversion functions](http://smealum.github.io/ctrulib/utf_8h.html) to convert the UTF-16 string to UTF-8, which is what everything expects.

**Comment by MarcuzD** [comment]
Ohh, okay, thanks :P I forgot that there's the utils/utf.h in the source code.

But the weirdest thing I experienced is that if I include wchar.h *anywhere* in the project, every function that prints to stdout/stderr (except "puts") causes a softlock, even if only printing char*
