### ISSUE TITLE
Undefined reference to `__tdata_lma_end', `__tdata_lma', `__tls_start' and `__tls_end'.

### ISSUE THREAD

**Issue by Substance12** [smealum/ctrulib#240]
I was trying to build yellows8's hblauncher_loader. After updating a bit the code to the post-refactor ctrulib, I keep getting these errors on compiling:

```makefile
linking hblauncher_loader.elf
c:/devkitPro/libctru/lib\libctru.a(syscalls.o): In function `__system_initSyscalls':
c:/devkitPro/libctru/source/system/syscalls.c:57: undefined reference to `__tdata_lma_end'
c:/devkitPro/libctru/source/system/syscalls.c:57: undefined reference to `__tdata_lma'
c:/devkitPro/libctru/source/system/syscalls.c:57: undefined reference to `__tls_start'
c:/devkitPro/libctru/lib\libctru.a(thread.o): In function `threadCreate':
c:/devkitPro/libctru/source/thread.c:64: undefined reference to `__tls_start'
c:/devkitPro/libctru/source/thread.c:64: undefined reference to `__tls_end'
c:/devkitPro/libctru/source/thread.c:64: undefined reference to `__tdata_lma_end'
c:/devkitPro/libctru/source/thread.c:64: undefined reference to `__tdata_lma'
collect2.exe: error: ld returned 1 exit status
```

I'm using the latest ctrulib commit. Any ideas on how to fix it?

**Comment by Steveice10** [comment]
Did you update devkitARM to r45?

**Comment by Substance12** [comment]
Yes.

**Comment by urherenow** [comment]
If hblauncher_loader isn't compatible with 1.1 yet, just rename devkitpro/libctru with a "_" then grab 1.0 and make -> make install.

That's the fastest way without having to think about it, anyway...

**Comment by Substance12** [comment]
But that wouldn't fix the problem, it would be a workaround.

**Comment by yellows8** [comment]
This is an issue with the separate .ld hblauncher_loader uses, please move this into an issue here: https://github.com/yellows8/hblauncher_loader/issues
