### ISSUE TITLE
Changes in inet.h

### ISSUE THREAD

**Issue by asthemic** [smealum/ctrulib#248]
I use make install on libctru and it didn't throw up any errors until.

However, when using libctru to compile other projects, the changes in (
https://github.com/smealum/ctrulib/commit/28b377511827af81d4b9e6b41bb9bc7ab289566e) cause errors:
`c:/devkitPro/libctru/include/arpa/inet.h:34:53: error: expected ',' or '...' before 'src'
  const char *inet_ntop(int af, const void *restrict src, char *restrict dst, socklen_t size);`

`c:/devkitPro/libctru/include/arpa/inet.h:35:52: error: expected ',' or '...' before 'src'
  int        inet_pton(int af, const char *restrict src, void *restrict dst);`

Manually removing lines 34 and 35 completes the compile. 
Not tested the completed compile to see if it is functional yet.

**Comment by Lectem** [comment]
It seems you might not be compiling using C99 or later, hence the restrict keyword isn't recognized.
C++ projects might suffer from the same issue ?

**Comment by asthemic** [comment]
*confused*

This is a using a basic build of devkitPro 1.6.0 with all optional extras added, the readme doesn't mention making any changes. 
Project that was directly using inet.h is https://github.com/Steveice10/FBI which you are right in that it is a C++.

**Comment by asthemic** [comment]
Excellent, that builds fine.
