### ISSUE TITLE
`socket()` does not replace protocol parameter with 0 when appropriate

### ISSUE THREAD

**Issue by ss23** [smealum/ctrulib#250]
I'm unsure how to fix this issue, and the title is probably misleading.

When user code does something like `socket(AF_INET, SOCK_STREAM, 0);` it will work on both the 3DS and a host system.
When user code does `AF_INET, SOCK_STREAM, IPPROTO_TCP);`, it works on the host system but not the 3DS. Some libraries explicitly pass in a protocol instead of 0.

This behavior is documented on https://www.3dbrew.org/wiki/SOCU:socket

It feels appropriate to have some compatibility code in ctrulib to ensure that the call works as expected on the 3DS. I'm not sure how it would be best to implmement, but some suggestions would be:
* set the protocol to 0 no matter what
* throw an error when the protocol is not 0 (not compatibility, but better than current behavior)
* if AF_INET, SOCK_STREAM, and TCP, then protocol = 0 (and the same for UDP as required)

Happy to make a PR for any one of these if someone would like me to, but was wondering what everyone else thought was best.

**Comment by Lectem** [comment]
Changing the value of IPPROTO_TCP/UDP isn't an option since it needs to work with get/setsockopt.
I would say that the best option is:
* if AF_INET, SOCK_STREAM, and TCP, then protocol = 0 (and the same for UDP as required)
