### ISSUE TITLE
repo history is a mess

### ISSUE THREAD

**Issue by WinterMute** [smealum/ctrulib#262]
@yellows8 @ksanislo @yuriks 
The last merge has turned the repo history into spaghetti.

The best way to fix it is probably to revert to https://github.com/smealum/ctrulib/commit/4f1c3e53e225fff50fcd85e58642f0cedb56568d and force push then cleaning up the branch that was merged to remove the double commits and merge upstream noise caused by merging upstream rather than rebasing.

I think we may need some guidelines for contributions similar to those provided by citra at https://github.com/citra-emu/citra/wiki/Typical-Git-Workflow

Any thoughts?

**Comment by WinterMute** [comment]
Caused by https://github.com/smealum/ctrulib/pull/258

**Comment by Lectem** [comment]
I would reset to 42ce1d87928e41aa08a16d6d68dc1f34ff11aa56 and then use cherry-pick to get a clean PR.

> I think we may need some guidelines for contributions similar to those provided by citra at https://github.com/citra-emu/citra/wiki/Typical-Git-Workflow

Sounds like a good idea

**Comment by WinterMute** [comment]
Cleaned up history with https://github.com/smealum/ctrulib/commit/5e84447219f964dec9cb7ed8395440bc48fa2214

**Comment by Steveice10** [comment]
Probably can be closed?
