### ISSUE TITLE
Application crash using secondary threads

### ISSUE THREAD

**Issue by Rinnegatamante** [smealum/ctrulib#264]
I recently updated ctrulib used in lpp-3ds and it caused the interpreter to crash whenever a sound streaming is trying to get updated.
I tried also to change the svcCreateThread calls with threadCreate ones but the problem still exists.
(I'm using mfloat-abi=softfp for vorbisfile support)

This is the commit which probably broke secondary threads: https://github.com/Rinnegatamante/lpp-3ds/commit/14b93f42d05625010835e440327daaf0a9e5f9cb

This is where secondary thread is created: https://github.com/Rinnegatamante/lpp-3ds/blob/master/source/luaSound.cpp#L1605-L1615

And this is the code executed by secondary thread (updateStream event is called in main loop): https://github.com/Rinnegatamante/lpp-3ds/blob/master/source/luaSound.cpp#L812-L900

**Comment by Rinnegatamante** [comment]
Looks like the problem solved using threadCreate. When i tried to use it first i was passing wrong values. That's what probably caused the crash. (It still crashes if i use svcCreateThread but not a big deal).

**Comment by WinterMute** [comment]
Is there any chance you could check your own code more thoroughly before you open libctru issues in future?

**Comment by fincs** [comment]
For the record: directly creating threads using svcCreateThread is **no longer supported**. Please make sure to use threadCreate from now on, as it takes care of setting up all necessary behind-the-scenes structures for the C stdlib and the supporting locking runtime to function properly.

**Comment by Rinnegatamante** [comment]
@WinterMute the code sounded to me legit, there weren't any advice about svcCreateThread no more usable (at least reading doxygen documentation or functions comments in header files) so opening an issue sounded correct to me.

**Comment by Lectem** [comment]
@Rinnegatamante it still works, after all it is nothing but a service call. The fact that it is no longer advised is that newlib wasn't thread-safe before, while now it is if using threadCreate.
What @WinterMute meant is that if it crashed, it is not the fault of svcCreateThread nor ctrulib, you simply had a race condition somewhere, or were passing bad stuff to svcCreateThread.
The fact is, you're not even taking the time to read the documentation as shown by this commit https://github.com/Rinnegatamante/lpp-3ds/commit/29e67a2abb88bda881317c0de81d72791364ea19,
you're not even calling threadFree anywhere, and there are way too many similar problems in your codebase.

**Comment by Rinnegatamante** [comment]
https://github.com/smealum/ctrulib/blob/master/libctru/include/3ds/thread.h#L26

That's why i'm not calling a threadFree...

**Comment by Lectem** [comment]
My bad on this one, rest is still valid

**Comment by Lectem** [comment]
Actually, since you are using svcExitThread instead of threadExit, you indeed need to call threadFree.

The API expects you to either call threadExit or return from your function.
While it is normal since the API expects you to only use the API and not services, it might be worth adding a note about this to the documentation @fincs  ?

**Comment by fincs** [comment]
We can add a note to the documentation, no problem.
