### ISSUE TITLE
Sharedmem handling for httpc results in crash on exit

### ISSUE THREAD

**Issue by Bownairo** [smealum/ctrulib#268]
The sharedmem handling - for me at least - allows for POST data to be sent only if the buffer size is set to be a multiple of 0x1000. If the buffer size is set to one of these values, the POST request sends, but the app fails to close to the homebrew launcher properly, resulting in a frozen 3DS. If the buffer is set to any other size, the app will exit to the homebrew launcher properly, but fail to open a context. @yellows8

**Comment by Lectem** [comment]
https://github.com/smealum/ctrulib/blob/master/libctru/include/3ds/services/httpc.h#L34
shared memory must be page aligned, see the doc

**Comment by Bownairo** [comment]
From my understanding, all aligning of memory now takes place in httpcInit, a function in httpc.c, since a recent commit.

**Comment by Lectem** [comment]
> sharedmem_size should be aligned to 0x1000-bytes
The doc is talking about the size, not the buffer itself (which as you said is always aligned since it's done by httpcInit), though I agree the wording can be confusing. 
In a general way, shared memory is expected to be page-aligned and its size a multiple of the page size.

**Comment by Bownairo** [comment]
When the size is a multiple of the page size (and 2) the application posts, but fails to exit properly. If the size isn't aligned to the page size (or 2), the application does not post, and no exit error occurs. That's why I assumed the error to occur in the sharedmem handling.

**Comment by yellows8** [comment]
No, the sharedmem code is fine(using it myself). What code are you using?

**Comment by Bownairo** [comment]
This results in a successful POST...

```
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <inttypes.h>
#include <3ds.h>

int main()
{
	gfxInitDefault();
	consoleInit(GFX_BOTTOM, NULL);

	httpcContext context;
	u32 bufferSize = 0x1000;
	char *url = "http://192.168.8.101/";

	httpcInit(bufferSize);
	httpcOpenContext(&context, HTTPC_METHOD_POST, url, 1);
	httpcAddPostDataAscii(&context, "Test1", "Test2");
	httpcBeginRequest(&context);

	// Main loop
	while (aptMainLoop())
	{
		gspWaitForVBlank();
		hidScanInput();
		u32 kDown = hidKeysDown();
		
		if (kDown & KEY_START)
			break; // break in order to return to hbmenu

		if (kDown & KEY_SELECT)
			httpcCloseContext(&context);

		gfxFlushBuffers();
		gfxSwapBuffers();
	}

	httpcExit();
	gfxExit();
	return 0;
}
```
(debugging removed for the sake of size)

![wireshark](https://cloud.githubusercontent.com/assets/7826872/13587792/8cf5b3b0-e498-11e5-9fc1-5a91856c6014.png)

but upon exiting the application,

![3ds](https://cloud.githubusercontent.com/assets/7826872/13587644/9e09488e-e497-11e5-9980-2476de5e4bdf.png)

**Comment by Lectem** [comment]
This sample works fine for me on n3ds 10.3.0-28E with hax 2.5.
I used http://lectem.fr/ as url, and it gave me status code 200.
Pressing select or not, it exits just fine.

**Comment by Bownairo** [comment]
Do you use the standard homebrew launcher? Is it possible that gridlauncher is creating the issue? If so is that a problem with gridlauncher or with ctrulib?

**Comment by Lectem** [comment]
I'm using the 3ds_hb_menu that was shipped with hax2.5. Could you try the latest 3ds_hb_menu ? What is your *hax version ? Perhaps something broke, or yeah, just gridlauncher.

**Comment by Bownairo** [comment]
I'll give it a try and report.

**Comment by Bownairo** [comment]
Using standard homebrew launcher does not crash upon exit.

**Comment by Lectem** [comment]
> Using standard homebrew launcher does not crash upon exit.

Grid launcher is the issue then, it probably has problems with its shared mem handling or something.

**Comment by ksanislo** [comment]
@Bownairo, Just a random thought here, but it might be that in your example you're failing to close the context when you're finished with it. Also, I believe there's a note somewhere in the wiki indicating that you must read all returned data from the context or it will freeze when leaving as well (but you /might/ be able to CancelConnection to avoid that). I've seen that cause things using httpc to hang when exiting, as well as fail to start anything up without a reboot after ~6 contexts have gone unclosed.
