### ISSUE TITLE
broken code with news:s

### ISSUE THREAD

**Issue by WoniMK7** [smealum/ctrulib#278]
This doesn't work when using news:s
[here.](https://github.com/smealum/ctrulib/blob/master/libctru/source/services/news.c#L30)

**Comment by Lectem** [comment]
3dbrew (https://www.3dbrew.org/wiki/NEWSS:AddNotification) gives 0x000100C6 while the code in ctrulib uses 0x000100C8, probably because of this.

**Comment by yellows8** [comment]
The command-header specifies more translate-params than what the code actually initialized, hence kernel-panic.

**Comment by Lectem** [comment]
@WoniMK7 could you test this #279 ?

**Comment by WoniMK7** [comment]
Works
