### ISSUE TITLE
makefile error

### ISSUE THREAD

**Issue by EpicZ501** [smealum/ctrulib#284]
I am on Ubuntu and when I try to do make command in terminal it says:
Makefile:10: /opt/devkitpro/devkitARM/base_rules: No such file or directory
make: **\* No rule to make target '/opt/devkitpro/devkitARM/base_rules'.  Stop.

How do I fix this
Note: I am using Virtualbox just in case you need to know

**Comment by urherenow** [comment]
Why? Why virtualbox? There are devkitPro installers for Winxows and Mac (Also compatible with linux).

**Comment by urherenow** [comment]
:X

*Windows

**Comment by EpicZ501** [comment]
I am doing Smashbroshax and I have windows

**Comment by EpicZ501** [comment]
Just tell me if i am doing anything wrong I've been trying to get smashbroshax for like 2 months now

**Comment by urherenow** [comment]
1) This repo is for ctrulib, not smashbroshax
2) This is not a forum. Ask for help at gbatemp or something.
