### ISSUE TITLE
RomFS no longer works without specifying "romfs:/"

### ISSUE THREAD

**Issue by flarn2006** [smealum/ctrulib#293]
I've always liked how files could be loaded from RomFS without having to specify it's on RomFS. I didn't know how it knows to load it from there, instead of the SD card, but it worked. But now it doesn't work. So now if I want to use RomFS for the CIA build (which is really the best way) I can't write code that will work for both versions at once. I have to find some way of detecting at runtime whether or not to load it from RomFS, because both the 3DSX and CIA are ultimately built from the same [ELF](https://static-cdn.jtvnw.net/emoticons/v1/243/3.0).

Can you please put this back to the way it was before? Or if not, is there anything I can specify in a single path that will make it load from RomFS if present, or the app directory on the SD card otherwise?

**Comment by profi200** [comment]
Old versions of ctrulib changed the default directory to "romfs:/" if romfsInit() is called. That breaks some older homebrews which assume "sdmc:/" is default. You should always explicitly specify the mountpoint to avoid such issues.

**Comment by fincs** [comment]
You can just use `chdir("romfs:/");` after `romfsInit()` to replicate the old behaviour. Oh, and 3dsx has RomFS support too and it is the best way to load assets as well (please make sure to be using an up-to-date Makefile).

**Comment by flarn2006** [comment]
Oh okay, thanks; that will probably solve my problem.

[Relevant](https://xkcd.com/1172/)

**Comment by flarn2006** [comment]
By the way, where do I find the up-to-date makefile?

Also, I just noticed what you did with the word "best". That's actually what I thought of when I saw the word "best" in a different color, but I wasn't expecting it to actually be that. :laughing:

**Comment by fincs** [comment]
Take a look at the [Makefile](https://github.com/devkitPro/3ds-examples/blob/master/romfs/Makefile) in the RomFS example.

**Comment by flarn2006** [comment]
Okay, thanks.
