### ISSUE TITLE
FSUSER_GetSdmcCid seems broken(?)

### ISSUE THREAD

**Issue by joel16** [smealum/ctrulib#306]
So I'm trying to get the SDMC CID, but every time I try using it, my 3DS just hangs. I'm not too sure if I'm using it correctly so here goes:

There are three ways I tried it:

1:
Result res = FSUSER_GetSdmcCid(NULL, 0x10);
printf("\x1b[32m*\x1b[0m CID: (%ld)!\n", res);

2:
u8* out;
FSUSER_GetSdmcCid(out, 0x10);
if (out != NULL)
	printf("\x1b[32m*\x1b[0m CID2: %s \n", out);

3:
u8* out = 0;
FSUSER_GetSdmcCid(out, 0x10);
printf("\x1b[32m*\x1b[0m CID: %u \n", (unsigned)out);

Neither of the 3 worked, and all of them crashed my 3DS. I had to hard reset (even for the CIA build). I may just not be using it correctly, if so can someone help me out?

**Comment by Lectem** [comment]
It expects a pointer to a buffer, and its length. You are giving it a null pointer and 0x10 as length, so of course it is not working.
You need to allocated some memory for the buffer.

**Comment by fincs** [comment]
Closing issue due to user error.



( ͡° ͜ʖ ͡°)

**Comment by joel16** [comment]
Sorry about that, should have read the documentation better. 
Anyways, I tried this:

u8* buffer = (u8*)malloc(0x10);
FSUSER_GetSdmcCid(buffer, 0x10);
printf("\x1b[32m*\x1b[0m SDMC CID: %s \n", buffer);

But it's not giving me any result (NULL, basically). The reason I used 0x10 as the length is because that's what the header tells me to do. So I also tried printing the unsigned result, and that's giving me something different (It's definitely not the CID).
I feel like it's something quite simple, I'm just not putting it right.

**Comment by fincs** [comment]
The SDMC CID is binary data, you cannot print it directly using `%s`. You may want to look into converting raw binary data into a hex string first.

**Comment by Lectem** [comment]
(u8)malloc(0x10);

You're casting to u8 not u8*. It truncates the pointer and thus the memory address is wrong

**Comment by joel16** [comment]
Sorry for being so late. I got busy with other programs. @fincs I do know how to convert raw binary data into hex format using %02X
I never thought it was that simple, my bad haha
Thank you, I've sorted out the issues.
