### ISSUE TITLE
aptMainLoop() seems to not handle correctly sleepmode while in the home menu 

### ISSUE THREAD

**Issue by nop90** [smealum/ctrulib#313]
When from an application you go in the home menu pressing the Home button, if you close the 3ds case, opening it again the screens remain black and the system seems to be frozen.

Obviusly this is related to application installed from a CIA package.

**Comment by fincs** [comment]
I remember something like this happened before APT was rewritten. Can you verify that a test application (e.g. a simple 'hello world') compiled with the very latest libctru commit exhibits this issue?

**Comment by nop90** [comment]
I can confirm that with the latest ctrulib this problem is solved.

Sorry for not checking it before postig, I updated ctulib in july, only few days before the new aptMainLoop() was released.

Thank you.
