### ISSUE TITLE
CSND or NDSP can not get the current playback time?

### ISSUE THREAD

**Issue by ioozhuangzi** [smealum/ctrulib#315]
CSND or NDSP can not get the current playback time? No available functions found in libctru Documentation. What can I do to achieve this function? thx...

**Comment by fincs** [comment]
CSND is obsolete and deprecated in favour of NDSP.
What do you mean by playback time? If you mean the sample playback position, [ndspChnGetSamplePos](https://github.com/smealum/ctrulib/blob/master/libctru/include/3ds/ndsp/channel.h#L71) exists.

**Comment by ioozhuangzi** [comment]
@fincs Probably understand. I'll try it first.Thank you for your answer~~
