### ISSUE TITLE
Documentation too old

### ISSUE THREAD

**Issue by ErmanSayin** [smealum/ctrulib#322]
Looks like the last commit on the documentation (gh-pages) was done almost a year ago.

https://github.com/smealum/ctrulib/tree/gh-pages

This should be updated to avoid confusion

**Comment by udemiko** [comment]
The documentation refers to v1.1.0, which is the latest official release shipping with devkitpro.
Until a new tagged release, you can use doxygen to generate docs from the cloned repo.

**Comment by WinterMute** [comment]
New release, docs updated accordingly.
