### ISSUE TITLE
Unicode font support/examples

### ISSUE THREAD

**Issue by deltabeard** [smealum/ctrulib#328]
Hello,

Currently, when printing unicode characters such as "ろん -「おちゃめ機能」FUKKIRETAＸ９-29-q7YnyUmY" they appear as incorrect ASCII characters as shown below (Shown next to "2: "):
![2016-12-31-110026_400x480_scrot](https://cloud.githubusercontent.com/assets/3747104/21577241/072e7592-cf4c-11e6-96c8-c2ec4c7d9ae0.png)

I know that using the system font example, or with sftdlib, unicode text can be printed. But is there a way to print unicode characters on the console? 

Thanks.

**Comment by fincs** [comment]
The console is only meant to quickly display ASCII text for debugging or prototyping purposes. What you see are the raw UTF-8 code units comprising the strings you are trying to print, as interpreted through whatever old 8-bit codepage the console font contains data for. If you need serious text rendering, you should use the system font or any other text rendering mechanism which supports Unicode characters.

In the future it is possible that we will consider expanding the console code in this way, however don't count on it.
