### ISSUE TITLE
[Request] Simple "downloadFile()" function

### ISSUE THREAD

**Issue by thebeastgamer25** [smealum/ctrulib#337]
I would like this added since the current method of downloading files is crazy.

**Comment by deltabeard** [comment]
The http_download(const char *url) function in this [example](http://smealum.github.io/ctrulib/http_2source_2main_8c-example.html) provides what you want already.

**Comment by fincs** [comment]
Closing. libctru is not supposed to be a kitchen sink of random utility functions. The example projects exist for a reason.

**Comment by KironDevCoder** [comment]
@deltabeard the example project is... deleted?

**Comment by deltabeard** [comment]
It seems to have moved to [here](https://smealum.github.io/ctrulib/network_2http_2source_2main_8c-example.html). All the ctrulib examples may be found [here](https://smealum.github.io/ctrulib/examples.html).

**Comment by KironDevCoder** [comment]
But I want the content of it, I tried this example but it just tells me some stuff like the content size... I just want the content of it.

**Comment by Oreo639** [comment]
The example application does get the content (using httpcDownloadData()) and it stores the downloaded data in memory in a buffer called buf (which after download the example tries writing to the framebuffer). If you want to write it to a file, you can use fwrite. 
Although I don't think the file it is trying to download exists anymore.

Correct me if I am wrong.

**Comment by mtheall** [comment]
@deltabeard example lives here: https://github.com/devkitPro/3ds-examples/tree/master/network/http

@Oreo639 yes, that example's url gives me a 404.

Additionally, we now have a curl portlib.

**Comment by deltabeard** [comment]
@mtheall Thank you for linking the source code. I linked the documentation deliberately in this case.

**Comment by KironDevCoder** [comment]
This still doesn't work for me tho.

**Comment by deltabeard** [comment]
Could you be a little more description with what isn't actually working for you please?
