### ISSUE TITLE
Request: add guide for deprecated code

### ISSUE THREAD

**Issue by rrooij** [smealum/ctrulib#402]
Some GPUCMD functions have been marked as deprecated, but there is no documentation on how to replace it.

I only found a mention of new methods to use in a commit message.

It would be nice to have this documentation as it will make it a lot easier for homebrew developers to renew their applications. For instance, snes9x_3ds is still not ported to libctru 1.4.

**Comment by fincs** [comment]
You're supposed to use [citro3d](https://github.com/fincs/citro3d). There are [citro3d examples](https://github.com/devkitPro/3ds-examples/tree/master/graphics/gpu) too.
