### ISSUE TITLE
CSND adpcm state address hardcoded

### ISSUE THREAD

**Issue by mariohackandglitch** [smealum/ctrulib#404]
https://github.com/smealum/ctrulib/blob/fcf9ca767b640965b9e98c482d3e0cfaca862a59/libctru/source/services/csnd.c#L530-L535

This part of the code is hardcoded to get the adpcm state from the position before the data buffer. While this may be "useful" in some case, in others where the data is being read from a file (bcwav in this case) it is not useful at all. If it wasn't hardcoded it would be possible to just load the file to memory and process the data there, however since the data buffers for different channels are next to each other, it's not possible to use that approach.

Note that while it's not recommended to use csnd to play music, it is very useful for sound effects.

**Comment by fincs** [comment]
CSND should be used anymore, and we don't plan adding any features to it at all.

There's no reason to choose CSND over NDSP for the purposes of playing sound effects. NDSP gives you 24 independently mixed sound channels (just like CSND), and way more control over what is played and effects.

**Comment by mariohackandglitch** [comment]
It's the only workaround if ndsp is not available.

In any case, why have something that partly works and not just remove it at all?

**Comment by profi200** [comment]
It has its use cases. It's the only one which would reliably work from a different (background) process alongside a game/homebrew.

**Comment by mariohackandglitch** [comment]
What profi200 said, that's why I want to use it. DSP service is being used by the game and it's not a good idea to use it. csnd in the other hand works flawlessly.
