### ISSUE TITLE
frdGetSessionHandle declared with different name in header

### ISSUE THREAD

**Issue by Slattz** [smealum/ctrulib#417]
[frdGetSessionHandle](https://github.com/smealum/ctrulib/blob/master/libctru/source/services/frd.c#L63) is named `frdSessionGetHandle` in [frd.h](https://github.com/smealum/ctrulib/blob/master/libctru/include/3ds/services/frd.h#L100).
This leads to a `undefined reference` compilation error when using this function.

It's easily fixable by the user by manually changing it in `frd.h`, but I made an issue here anyways as it is something that has gone unnoticed.

**Comment by fincs** [comment]
Feel free to fork/submit a PR to correct this.
