### ISSUE TITLE
httpc get content of webpage

### ISSUE THREAD

**Issue by KironDevCoder** [smealum/ctrulib#436]
I am trying to get my 3ds homebrew app to get content of a webpage using httpc. Or maybe even download them. Any1 knows how this must be done?

**Comment by mtheall** [comment]
https://github.com/devkitPro/3ds-examples/tree/master/network/http

**Comment by KironDevCoder** [comment]
didn't work for me

**Comment by KironDevCoder** [comment]
@mtheall I want the content, not the size of the content

**Comment by mtheall** [comment]
The variable "buf" in that function contains the content.

**Comment by KironDevCoder** [comment]
And... how do I get a char* out of it? Sorry, I'm pretty new to C

**Comment by WinterMute** [comment]
This is an issue tracker for reporting bugs it's not for asking general questions. Your questions are better asked on the devkitPro forums @ https://devkitpro.org/viewforum.php?f=39

**Comment by badda71** [comment]
Yeah but the devkitpro forum is moderated and IMHO only few of the questions asked are actually posted - speaking from my own experience ...
