### ISSUE TITLE
citro2d performance appears to have been affected by latest update

### ISSUE THREAD

**Issue by TheGag96** [smealum/ctrulib#459]
Hi there. I recently updated all of devkitARM's packages through dkp-pacman, and after recompiling my homebrew with everything, I found that my call to `C2D_SpriteSheetLoad` from citro2d now takes an obscene amount of time (about 1.5 seconds on o3ds) for the spritesheet I was trying to load, where it took like 1/10th of the time before. 

Citro3d's recent changes aren't the culprit, and citro2d itself didn't change very much recently (and nothing related to spritesheet loading), so my only guess is that recent ctrulib changes had something to do with it. My only other guess is something in devkitPro's move to GCC 10.1, but I'm not sure. I'd like to try recompiling an older ctrulib, but I can't even compile it for some reason:

```
In file included from /opt/devkitpro/devkitARM/arm-none-eabi/include/c++/10.1.0/stdlib.h:36,
                 from /home/grayson/Packages/ctrulib/libctru/source/allocator/mem_pool.h:3,
                 from /home/grayson/Packages/ctrulib/libctru/source/allocator/vram.cpp:8:
/opt/devkitpro/devkitARM/arm-none-eabi/include/c++/10.1.0/cstdlib:232:11: error: 'strtold' has not been declared in '::'
  232 |   using ::strtold;
      |           ^~~~~~~
/opt/devkitpro/devkitARM/arm-none-eabi/include/c++/10.1.0/cstdlib:252:22: error: 'strtold' has not been declared in '__gnu_cxx'
  252 |   using ::__gnu_cxx::strtold;
      |                      ^~~~~~~
```

Really looks like my installation is broken somehow, but I'm not sure what to do about it. Any ideas as to what this might be? Thanks!

**Comment by WinterMute** [comment]
This probably isn't a libctru issue and will be difficult to look at without a testcase showing the issue for us to look at. I suggest starting a thread in the forums at https://devkitpro.org/viewforum.php?f=39 and providing some code, including the offending spritesheet.

**Comment by TheGag96** [comment]
Just posted - when my post gets approved (by you, maybe?), please take a look. Thank you!
