### ISSUE TITLE
httpcOpenContext fails after exactly 8 times, consistently

### ISSUE THREAD

**Issue by zeta0134** [smealum/ctrulib#66]
When opening http contexts to perform file downloads, every attempt after the 8th fails consistently, with the same error code, somewhere during the call to httpcOpenContext.

To reproduce this, I modified the http download example, and got it to repeatedly download files in a loop. It's hosted here: http://darknovagames.com:1337/3ds/http_context_test.zip. This is fairly straightforward; run the code, press A repeatedly, and after the 8th call to httpcOpenContext(), it fails consistently.

I'm testing on a 3DS XL, using firmware version 9.2.0-20U. This is through Ninjhax; I lack the ability to test on anything else. This is pretty weird; it feels like a resource is not being released somewhere, but httpcCloseContext() is definitely being called.

**Comment by zeta0134** [comment]
This is confirmed fixed on my end.

**Comment by celcodioc** [comment]
It seems to me that this has not been fixed yet: https://github.com/DownloadMii/DownloadMii/issues/24 (looks like everyone is experiencing this)

@zeta0134's modified example app doesn't work either for me, so I'm not sure what's going on. I'm using Ninjhax 1.1 (3DS XL, 9.2.0-20E), and the latest libctru commit (9fec42f38fd2a975a31e847bd095dba0ae4db8e2).

**Comment by WinterMute** [comment]
Are you absolutely sure that you're using the latest libctru? @zeta0134's test code is working perfectly for me on the same setup with this patch (Ninjhax 1.1, 3DS XL, 9.2.0-20E). Is there some other version of that code that's failing?

**Comment by plutooo** [comment]
Also can you check return value of every single httpcCloseContext? Maybe your code is leaking contexts.

**Comment by filfat** [comment]
@plutooo Pretty sure it isn't: https://github.com/DownloadMii/DownloadMii/edit/master/source/download.cpp

**Comment by plutooo** [comment]
Read my comment again.

**Comment by filfat** [comment]
@plutooo  i were referring to the leaking part :)

**Comment by celcodioc** [comment]
It always closes with code 0 on my build, I assume that's what's supposed to happen?

Also, now that I'm getting the return codes from `httpcCloseContext`, for some reason the ninth `httpcOpenContext` doesn't even return an error; it simply freezes the 3DS (how that's related to storing that return value I have no idea). No problems running the apps in 3dmoo, except this message when calling `httpcCloseContext`:

```
>> svcSendSyncRequest (0x32)
http_c_SyncRequest (line 217): CloseContext 0dadbb2a --stub--

>> svcCloseHandle (0x23)
svcCloseHandle: svcCloseHandle undefined for handle-type "service".
```

**Comment by plutooo** [comment]
@filfat Me too. httpcCloseContext() can fail (return non-zero) and thus leak handles.

@celcodioc Yeah, that's correct. Sounds like you might be leaking something/somewhere else. Maybe you could modify 3dmoo to verify that all handles are closed/cleaned up correctly.
