### ISSUE TITLE
About the SSL Service (2)

### ISSUE THREAD

**Issue by linoma** [smealum/ctrulib#74]
Ok, it is switching to the SSL connection but httpcGetResponseStatusCode returns 0xd8a0a03c with statuscode c3460000, The request is on port 443 but I think the certificate is invalid, can you help me?

**Comment by yellows8** [comment]
You didn't really need to open another issue for this - but anyway, ctrulib doesn't support the HTTPC cmd for adding a trusted root CA atm.

**Comment by linoma** [comment]
exccuse me the prevoius isuues was closed. Anyway Im trying with a custom HTTPC_AddTrustedRootCA the command return 0 (not errors) but during the request the same error occur.

**Comment by yellows8** [comment]
"[excuse] me the [previous] [issue] was closed" You could've still commented on that one. Anyway, can you get a pcap to make sure what the SSL failure really is?

**Comment by linoma** [comment]
excuse me againim using a tablet, anyway yes. the 3ds sends only small packets (150 bytes max) while the server sends packets containing the certificate. if you want to send the pcap

**Comment by yellows8** [comment]
Yeah upload it.

**Comment by linoma** [comment]
try here http://www.filedropper.com/test_9

**Comment by yellows8** [comment]
Either your HTTPC_AddTrustedRootCA code is wrong, or the data you're using with that cmd is wrong.

**Comment by linoma** [comment]
here's my code

Result HTTPC_AddTrustedRootCA(Handle handle, Handle contextHandle, u8* cert, int size)
{
	return 0;
	u32* cmdbuf=getThreadCommandBuffer();

	cmdbuf[0]=0x240082; //request header code
	cmdbuf[1]=contextHandle;
	cmdbuf[2]=size;
	cmdbuf[3]=(size<<4)|0xa;
	cmdbuf[4]=(u32)cert;
	
	Result ret=0;
	if((ret=svcSendSyncRequest(handle)))return ret;

	return cmdbuf[1];
}

**Comment by linoma** [comment]
here's my code

Result HTTPC_AddTrustedRootCA(Handle handle, Handle contextHandle, u8* cert, int size)
{
	return 0;
	u32* cmdbuf=getThreadCommandBuffer();

	cmdbuf[0]=0x240082; //request header code
	cmdbuf[1]=contextHandle;
	cmdbuf[2]=size;
	cmdbuf[3]=(size<<4)|0xa;
	cmdbuf[4]=(u32)cert;
	
	Result ret=0;
	if((ret=svcSendSyncRequest(handle)))return ret;

	return cmdbuf[1];
}

it return 0 and Im using a ssl certificate in der format.

**Comment by yellows8** [comment]
Perhaps you used the wrong cert for your root-CA.

**Comment by linoma** [comment]
I think with this func we add a certificate but We dont use it, I think the certificate must be selected.
