### ISSUE TITLE
memalign fails for the first call, succeeds for subsequent calls

### ISSUE THREAD

**Issue by zeta0134** [smealum/ctrulib#78]
The first call to memalign returns a valid-looking value, but attempting to use the memory causes a crash. Subsequent calls to memalign return valid values, but using them succeeds as one might expect.

Here's an example function I am testing to initialize sockets on the system:

    void initialize_sockets() {
      u32* first_bank = (u32*)memalign(0x1000, 0x100000);
      if (first_bank == nullptr) {
        debug_message("first memalign failed");
        return;
      }
      debug_message("first bank: " + string_from<unsigned int>((unsigned int)first_bank, true));
    
      u32* second_bank = (u32*)memalign(0x1000, 0x100000);
      if (second_bank == nullptr) {
        debug_message("second memalign failed");
        return;
      }
      debug_message("second bank: " + string_from<unsigned int>((unsigned int)second_bank, true));
    
      u32 ret = SOC_Initialize(second_bank, 0x100000);
      debug_message(string_from<unsigned int>(ret));
    }

Sample output on my system:
first bank: 0x8001000
second bank: 0x8102000

Modifying the code to pass first_bank in to SOC_Initialize causes it to crash. This is built against ctrulib version 74c37b4e87286f40000dea00b529126af5a7d4b8

Not sure what's going on; I suspect this has something to do with the recent changes to handle executable data regions perhaps?

**Comment by fincs** [comment]
smea fixed this in ed72f947.

**Comment by WinterMute** [comment]
that wasn't memalign that was fixed

**Comment by WinterMute** [comment]
Fixed with 168d967
