### ISSUE TITLE
GPU example doesn't compile with latest aemstro

### ISSUE THREAD

**Issue by neobrain** [smealum/ctrulib#86]
Last working version is smealum/aemstro@55bf5056d199e0e9ec3d136dc830ac45a49da074 . After that, trying to build yields these error messages:

    ~/devkitPro/ctrulib_refactor/examples/gpu> make
    test.vsh
    inconsisten uniform register assignment !
    inconsisten uniform register assignment !
    Traceback (most recent call last):
      File "aemstro/aemstro_as.py", line 503, in <module>
        parseLine(dvlb.getDVLP(), dvle, line, False)
      File "aemstro/aemstro_as.py", line 481, in parseLine
        dirList[name](dvlp, dvle, r.group(2))
      File "aemstro/aemstro_as.py", line 432, in parseUniform
        dvle.addInput((int(s[0][1:],0)+offset,int(s[1][1:],0)+offset,s[2]))
    ValueError: invalid literal for int() with base 0: ''
    examples/gpu/Makefile:158: recipe for target 'test.vsh.o' failed
    make[1]: *** [test.vsh.o] Error 1
    Makefile:122: recipe for target 'build' failed
    make: *** [build] Error 2

**Comment by Zal0** [comment]
Seems a bit more related to the test.vsh shader than aemstro. The compiler has changed but the shader is a bit outdated

**Comment by WinterMute** [comment]
https://github.com/smealum/ctrulib/blob/master/examples/gpu/README.md

**Comment by neobrain** [comment]
@WinterMute Shouldn't we be striving towards having a uniform code base, rather than things relying on outdated tools, possibly with different ctrulib examples relying on different versions on aemstro in the future? Is there any need to actually close this issue until someone fixes up the gpu example shaders for the more recent aemstro?

(in other words: having a note saying that an old aemstro version is required sounds like a workaround, not a solution)

**Comment by Zal0** [comment]
It doesn't work with that version either :(  (I have also been looking for the proper version of the ctrulib which compiles it, but no luck yet)

**Comment by smealum** [comment]
@neobrain it's obviously not meant to be a solution. the point is that this should be updated, and i've been wanting to do it for a while now but i just don't have time at the moment. please be patient.
