### ISSUE TITLE
Different charsets support

### ISSUE THREAD

**Issue by Rinnegatamante** [smealum/ctrulib#91]
Why not adding different charsets support (like UTF-8 and Latin1(ISO-8859-1)) to libctru functions? (Maybe using LC_COLLATE category returned by standard C setlocale function to interchange charset to use)

**Comment by mtheall** [comment]
We have added UTF-8 support to the filesystem code. We will probably merge it into the mainline code in the near future. I wouldn't count on full locale support except for "C" and "POSIX" locales. You could reasonably expect UTF-8 to be the only available character encoding.

**Comment by WinterMute** [comment]
This isn't something that libctru would ever support tbh and locale support is provided by newlib
