### ISSUE TITLE
Bug in HTTPC_AddRequestHeaderField function

### ISSUE THREAD

**Issue by LunarCookies** [smealum/ctrulib#92]
This line:

    cmdbuf[6]=(l1<<4)|0xA;

Should be:

    cmdbuf[6]=(l2<<4)|0xA;

**Comment by archshift** [comment]
Why not just create a pull request?

**Comment by WinterMute** [comment]
What happens if you try this without commit rights?

https://github.com/smealum/ctrulib/edit/master/libctru/source/services/httpc.c

**Comment by fincs** [comment]
GitHub will automatically perform a fork and a pull request for you when a person without commit access tries to edit a file.
